apiVersion: v1
kind: Service
metadata:
  name: studentapp-frontend-svc
  labels:
    app: studentapp-frontend
spec:
  selector:
    app: studentapp-frontend
  ports:
  - port: 8080
    targetPort: 8080